version: '2'
services:
  app:
    container_name: filestash
    image: tarielx/filestash
    restart: always
    environment:
        - APPLICATION_URL=
        - GDRIVE_CLIENT_ID=<gdrive_client>
        - GDRIVE_CLIENT_SECRET=<gdrive_secret>
        - DROPBOX_CLIENT_ID=<dropbox_key>
        - ONLYOFFICE_URL=http://onlyoffice
    volumes:
        - filestash:/app/data/state/

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver
    restart: always
    security_opt:
      - seccomp:unconfined

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    ports:
        - "443:443"
        - "80:80"
    volumes:
        - Caddyfile:/etc/caddy/Caddyfile

volumes:
    filestash: {}
