version: '2'
services:
  app:
    container_name: filestash
    image: tarielx/filestash:latest
    restart: always
    environment:
        - APPLICATION_URL=
        - GDRIVE_CLIENT_ID=<gdrive_client>
        - GDRIVE_CLIENT_SECRET=<gdrive_secret>
        - DROPBOX_CLIENT_ID=<dropbox_key>
        - ONLYOFFICE_URL=http://onlyoffice
    volumes:
        - filestash:/app/data/state/

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    ports:
        - "443:443"
        - "8335:80"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
    filestash: {}
